# travis-ci layout checking for layouts

sudo:
  - false

os:
  - linux

language:
  - python

python:
  - "3.6"

env:
  global:
    - PIPENV_IGNORE_VIRTUALENVS=1

# System setup
install:
  # Info about OS
  - uname -a

  # Prepare layouts-python package
  - pip install layouts

# Run test script(s)
script:
  - tests/python-test.py

